extends Node

@export var resolution:int = 20
@export var x_scroll = 0.01
@export var y_scroll = 0.01
@export var z_scroll = 0.01
var x = 0
var y = 0
var z = 0

@export_category("Conversions")
## DECIDE WHAT THE HELL A WIND IS. FORCE? SPEED ... 
@export var scale = 10 

func _ready() -> void:
	Globals.Wind = self

	$WindNoise.texture.height = resolution
	$WindNoise.texture.width = resolution
	$WindIllustrator.material.set_shader_parameter("texture_size", Vector2(resolution,resolution))

@onready var wind_texture_image:Image = Image.create_empty(resolution,resolution,false, Image.Format.FORMAT_RGB8 )

func _process(delta: float) -> void:
	delta = delta * Globals.WorldTime.scale
	#TODO: Consider slowing this, eg change wind only 3 times per day?
	# https://docs.godotengine.org/en/stable/classes/class_noisetexture2d.html
	#The class uses Threads to generate the texture data internally, so Texture2D.get_image() may return null if the generation process has not completed yet. In that case, you need to wait for the texture to be generated before accessing the image and the generated byte data:
	#Note: This will fetch the texture data from the GPU, which might cause performance problems when overused. Avoid calling get_image() every frame, especially on large textures.
	
	x += x_scroll * delta 
	y += y_scroll * delta 
	z += z_scroll * delta 
	
	$WindNoise.texture.noise.offset.x = (x)
	$WindNoise.texture.noise.offset.y = (y)
	$WindNoise.texture.noise.offset.z = (z)
	
	await $WindNoise.texture.changed
	wind_texture_image = $WindNoise.texture.get_image()


func colorToWindVector(c:Color):
	var length = c.r * scale
	var angle = c.g * 2 * PI
	var v = Vector2.from_angle(angle) * length
	return v

func towardsCenterVector(p:Vector2):
	return (Vector2(resolution,resolution)/2 - p).normalized() * scale


func getInPos( pos:Vector2 ):
	var positionInWindTexture = (pos + Globals.WorldMapSize/2 ) / Globals.WorldMapSize * resolution
	if(positionInWindTexture.x < 0 
	or positionInWindTexture.y < 0
	or positionInWindTexture.x > resolution 
	or positionInWindTexture.y > resolution ):
		return towardsCenterVector(positionInWindTexture)

	var val = wind_texture_image.get_pixelv(positionInWindTexture)
	return colorToWindVector(val)
	
