@tool
extends EditorPlugin

const ITEMS_DIR := "res://Entities/Items/"
const OUTPUT_DIR := "res://Entities/Items/Item_Lists"
const OUTPUT_FILE := OUTPUT_DIR+"/item_list_{type}.gd"

const supported_types = {
	"float": "0",
	"PriceCalculator": "PriceCalculator.new()",
	}


const DEBUG := false

var scan_timer := 0.0
const SCAN_INTERVAL := 3.0

var last_hash := ""
 
func debug_log(msg):
	if DEBUG:
		print("[InventoryItemGenerator] ", msg)


func _enter_tree():
	debug_log("Plugin enabled")
	set_process(true)


func _exit_tree():
	debug_log("Plugin disabled")
	set_process(false)


func _process(delta):
	scan_timer += delta

	if scan_timer >= SCAN_INTERVAL:
		debug_log("Scan interval reached. Starting scan.")
		scan_timer = 0.0
		scan_items()


func scan_items():
	debug_log("Opening directory: %s" % ITEMS_DIR)

	var dir := DirAccess.open(ITEMS_DIR)
	if dir == null:
		push_warning("InventoryItemGenerator: Items folder missing")
		debug_log("ERROR: Could not open items directory.")
		return

	var item_files := []

	dir.list_dir_begin()
	var file := dir.get_next()

	while file != "":

		debug_log("Found entry: %s" % file)

		if dir.current_is_dir():
			debug_log("Skipping directory: %s" % file)
		else:

			if file.ends_with(".tres") or file.ends_with(".res"):

				var path := ITEMS_DIR + file
				debug_log("Attempting to load resource: %s" % path)

				var res := ResourceLoader.load(path)

				if res == null:
					debug_log("Failed to load resource: %s" % path)

				elif res is InventoryItem:
					debug_log("Valid InventoryItem found: %s" % file)

					item_files.append({
						"id": res.id,
						"name": file.get_basename(),
						"path": path
					})

				else:
					debug_log("Resource is NOT InventoryItem: %s (type=%s)" % [file, res.get_class()])

			else:
				debug_log("Skipping non-resource file: %s" % file)

		file = dir.get_next()

	dir.list_dir_end()

	debug_log("Finished directory scan.")
	debug_log("Valid items found: %d" % item_files.size())

	item_files.sort_custom(func(a,b): return a.name < b.name)
	var new_hash := str(item_files, supported_types, self.get_script().source_code)

	debug_log("Generated hash: %s" % new_hash)
	debug_log("Previous hash: %s" % last_hash)

	if new_hash == last_hash:
		debug_log("No changes detected. Skipping regeneration.")
		return

	debug_log("Changes detected. Regenerating script.")
	last_hash = new_hash

	generate_script(item_files)


const base_text := """##### AUTOGENERATED SCRIPT. PLEASE DO NOT MODIFY #####
##### GENERATED BY {self} #####
@tool
extends Resource
class_name InventoryItemList_{type}

func _init():
	resource_local_to_scene = true

func get_item(item: InventoryItem) -> {type}:
	return (items.get(item, 0)) as {type}

func set_item(item: InventoryItem, value: {type}) -> void:
	items[item] = value

# --- GENERATED ITEM CONSTANTS ---


{item_constants}


# --- GENERATED FIELDS ---


{item_fields}


# --- GENERATED DICTIONARY ---

@export var items: Dictionary[InventoryItem, {type}] = {
{item_dictionary}
}


"""

var item_constants_template = "const {res_name} = preload(\"{res_path}\") \n"

var item_field_template = """
@export var {field_name}: {type}:
	get:
		return (items.get({const_name}, 0)) as {type}
	set(value):
		items[{const_name}] = value
"""

var item_dictionary_template = """
	{const_name}: {default_value},"""


func generate_script(items):
	clear_folder(OUTPUT_DIR)

	
	for type in supported_types:
		var text := base_text

		var OUTPUT_SCRIPT = OUTPUT_FILE.format({"type": type})
		debug_log("Generating script: %s" % OUTPUT_SCRIPT)
		debug_log("Items to generate: %d" % items.size())

		text = text.format({"type": type, "self":self.get_script()})

 
		# --------------------------------------------------
		# RESOURCE CONSTANTS
		# --------------------------------------------------

		var item_constants := ""
		for item in items:
			var res_name = item.name.to_upper()
			var res_path = item.path

			debug_log("Generating constant: %s" % res_name)
			var item_constant := item_constants_template.format({"res_name":res_name, "res_path":res_path })
			item_constants += item_constant 

		text = text.format({"item_constants": item_constants})


		# --------------------------------------------------
		# EXPORTED FIELDS
		# --------------------------------------------------


		var item_fields := ""
		for item in items:

			var field_name = item.name
			var const_name = item.name.to_upper()

			debug_log("Generating field with getter/setter: %s" % field_name)
			
			var item_field = item_field_template.format({
				"field_name":field_name,
				"const_name":const_name,
				"type":type,
			})
			item_fields += item_field
		
		text = text.format({"item_fields": item_fields})


		# --------------------------------------------------
		# DICTIONARY
		# --------------------------------------------------
		var item_dictionary = ""

		for item in items:
			var const_name = item.name.to_upper()
			var default_value = supported_types[type]

			debug_log("Adding dictionary entry: %s" % const_name)

			var dict_entry = item_dictionary_template.format({
				"const_name":const_name,
				"default_value":default_value,
			})
			item_dictionary += dict_entry

		text = text.format({"item_dictionary": item_dictionary})

 
		var file := FileAccess.open(OUTPUT_SCRIPT, FileAccess.WRITE)
		if file == null:
			push_error("InventoryItemGenerator: Could not write file.")
			debug_log("ERROR: Failed opening output file.")
			return
  
		file.store_string(text)
		file.close()

		debug_log("Script successfully written.")

		debug_log("Triggering editor filesystem rescan.")
		get_editor_interface().get_resource_filesystem().scan()

		print("InventoryItemList regenerated with %d items in %s" % [items.size(), OUTPUT_SCRIPT]) 



func clear_folder(folder_path: String) -> void:
	var dir := DirAccess.open(folder_path)

	if dir == null:
		push_error("Could not open folder: %s" % folder_path)
		return

	dir.list_dir_begin()
	var file_name = dir.get_next()

	while file_name != "":
		if !dir.current_is_dir():
			var full_path = folder_path + "/" + file_name
			DirAccess.remove_absolute(full_path)
		file_name = dir.get_next()

	dir.list_dir_end()
