##### AUTOGENERATED SCRIPT. PLEASE DO NOT MODIFY #####
##### GENERATED BY (res://addons/inventory_item_generator/inventory_item_generator.gd):<GDScript#-9223370429026990300> #####
#@tool
extends Resource
class_name InventoryItemList_float

func _init():
	resource_local_to_scene = true

func get_item(item: InventoryItem) -> float:
	return (items.get(item, 0)) as float

func set_item(item: InventoryItem, value: float) -> void:
	items[item] = value

# --- GENERATED ITEM CONSTANTS ---


const ITEM_STONE = preload("res://Entities/Items/item_stone.tres") 
const ITEM_WOOD = preload("res://Entities/Items/item_wood.tres") 



# --- GENERATED FIELDS ---



@export var item_stone: float:
	get:
		return (items.get(ITEM_STONE, 0)) as float
	set(value):
		items[ITEM_STONE] = value

@export var item_wood: float:
	get:
		return (items.get(ITEM_WOOD, 0)) as float
	set(value):
		items[ITEM_WOOD] = value



# --- GENERATED DICTIONARY ---

@export var items: Dictionary[InventoryItem, float] = {

	ITEM_STONE: 0,
	ITEM_WOOD: 0,
}
