##### AUTOGENERATED SCRIPT. PLEASE DO NOT MODIFY #####
##### GENERATED BY (res://addons/inventory_item_generator/inventory_item_generator.gd):<GDScript#-9223370426745288910> #####
@tool
extends Resource
class_name InventoryItemList_PriceCalculator

func _init():
	resource_local_to_scene = true

func get_item(item: InventoryItem) -> PriceCalculator:
	return (items.get(item, 0)) as PriceCalculator

func set_item(item: InventoryItem, value: PriceCalculator) -> void:
	items[item] = value

# --- GENERATED ITEM CONSTANTS ---


const ITEM_STONE = preload("res://Entities/Items/item_stone.tres") 
const ITEM_WOOD = preload("res://Entities/Items/item_wood.tres") 



# --- GENERATED FIELDS ---



@export var item_stone: PriceCalculator:
	get:
		return (items.get(ITEM_STONE, 0)) as PriceCalculator
	set(value):
		items[ITEM_STONE] = value

@export var item_wood: PriceCalculator:
	get:
		return (items.get(ITEM_WOOD, 0)) as PriceCalculator
	set(value):
		items[ITEM_WOOD] = value



# --- GENERATED DICTIONARY ---

@export var items: Dictionary[InventoryItem, PriceCalculator] = {

	ITEM_STONE: PriceCalculator.new(ITEM_STONE),
	ITEM_WOOD: PriceCalculator.new(ITEM_WOOD),
}


